const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST';
const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
const FETCH_TODOS_FAILED = 'FETCH_TODOS_FAILED';

const ADD_TODOS_REQUEST = 'ADD_TODOS_REQUEST';
const ADD_TODOS_SUCCESS = 'ADD_TODOS_SUCCESS';
const ADD_TODOS_FAILED = 'ADD_TODOS_FAILED';

const REMOVE_TODOS_REQUEST = 'REMOVE_TODOS_REQUEST';
const REMOVE_TODOS_SUCCESS = 'REMOVE_TODOS_SUCCESS';
const REMOVE_TODOS_FAILED = 'REMOVE_TODOS_FAILED';

export default {
  FETCH_TODOS_REQUEST,
  FETCH_TODOS_SUCCESS,
  FETCH_TODOS_FAILED,
  ADD_TODOS_REQUEST,
  ADD_TODOS_SUCCESS,
  ADD_TODOS_FAILED,
  REMOVE_TODOS_REQUEST,
  REMOVE_TODOS_SUCCESS,
  REMOVE_TODOS_FAILED,
};
